### ISSUE TITLE
The SAS URL for the cloud storage account is not specified.

### ISSUE THREAD

**Issue by TaurahSP** [SharePoint/sp-dev-samples#17]
publishing the webhook.mvcweb app results in the following error : System.ApplicationException: The trace listener AzureBlobTraceListener is disabled. ---> System.InvalidOperationException: The SAS URL for the cloud storage account is not specified.
 Use the environment variable 'DIAGNOSTICS_AZUREBLOBCONTAINERSASURL' to define it.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.RefreshConfig()
   --- End of inner exception stack trace ---""

#### Category

[ ] Bug

**Comment by attiqueahmed333** [comment]
Facing same exception while app service application is working fine in Azure but suddenly stopped working. Have you resolved ?? i believe this issue came from blob storage SAS token validation.
Any recommendation ?

System.ApplicationException: The trace listener AzureBlobTraceListener is disabled. ---> System.InvalidOperationException: The SAS URL for the cloud storage account is not specified. Use the environment variable 'DIAGNOSTICS_AZUREBLOBCONTAINERSASURL' to define it.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.RefreshConfig()
   --- End of inner exception stack trace ---
