### ISSUE TITLE
When i did as per the steps to run the react-generic-app for modern app development

### ISSUE THREAD

**Issue by muraray** [SharePoint/sp-dev-samples#26]
it does return this error 

λ gulp serve
[19:41:55] Using gulpfile C:\NTUC\UI\sp-dev-samples\Samples\react-generic-app\gulpfile.js
[19:41:55] Starting gulp
[19:41:55] Starting 'serve'...
[19:41:55] Starting subtask 'serve'...
[19:41:55] Finished subtask 'serve' after 172 ms
[19:41:55] Starting subtask 'pre-copy'...
[19:41:55] Finished subtask 'pre-copy' after 7.69 ms
[19:41:55] Starting subtask 'sass'...
(node:26476) ExperimentalWarning: The http2 module is an experimental API.
[19:41:55] Server started http://localhost:4321
[19:41:55] LiveReload started on port 35729
[19:41:56] Opening http://localhost:4321/index.html using the default OS app
  Request: '/index.html'
[19:41:56] Finished subtask 'sass' after 870 ms
[19:41:56] Starting subtask 'typescript'...
[19:41:56] [typescript] TypeScript version: 2.4.2
[19:41:56] Starting subtask 'text'...
[19:41:56] Starting subtask 'api-extractor'...
[19:41:56] Finished subtask 'api-extractor' after 987 μs
  Request: '/node_modules/react/dist/react.js'
  Request: '/node_modules/react-dom/dist/react-dom.js'
  Request: '/dist/react-app.js'
[19:41:56] Finished subtask 'text' after 14 ms
[19:41:58] Error - typescript - node_modules\@uifabric\utilities\lib\Customizer.d.ts(21,54): error TS2559: Type 'ICustomizerProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Calendar\CalendarDay.d.ts(29,55): error TS2559: Type 'ICalendarDayProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\ColorPicker.d.ts(7,55): error TS2559: Type 'IColorPickerProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DetailsList\DetailsHeader.d.ts(41,57): error TS2559: Type 'IDetailsHeaderProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DetailsList\DetailsRow.d.ts(43,54): error TS2559: Type 'IDetailsRowProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Dialog\DialogContent.d.ts(5,57): error TS2559: Type 'IDialogContentProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardActions.d.ts(2,63): error TS2559: Type 'IDocumentCardActionsProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardActivity.d.ts(2,64): error TS2559: Type 'IDocumentCardActivityProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardLocation.d.ts(2,64): error TS2559: Type 'IDocumentCardLocationProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardPreview.d.ts(2,63): error TS2559: Type 'IDocumentCardPreviewProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardTitle.d.ts(6,61): error TS2559: Type 'IDocumentCardTitleProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Fabric\Fabric.d.ts(5,50): error TS2559: Type 'HTMLProps<HTMLDivElement>' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Layer\LayerHost.d.ts(2,53): error TS2559: Type 'HTMLProps<HTMLElement>' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Pivot\PivotItem.d.ts(2,53): error TS2559: Type 'IPivotItemProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\pickers\AutoFill\BaseAutoFill.d.ts(5,56): error TS2559: Type 'IBaseAutoFillProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\pickers\BasePicker.d.ts(17,88): error TS2559: Type 'P' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\pickers\Suggestions\Suggestions.d.ts(3,62): error TS2559: Type 'ISuggestionItemProps<T>' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\components\pickers\Suggestions\Suggestions.d.ts(6,58): error TS2559: Type 'ISuggestionsProps<T>' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - typescript - node_modules\office-ui-fabric-react\lib\utilities\selection\SelectionZone.d.ts(13,57): error TS2559: Type 'ISelectionZoneProps' has no properties in common with type 'IBaseProps'.
[19:41:58] Error - 'typescript' sub task errored after 2.71 s
 TypeScript error(s) occurred.
(node:26476) UnhandledPromiseRejectionWarning: TypeError: options.message.replace is not a function
    at Object.module.exports.mapToWin8 (C:\NTUC\UI\sp-dev-samples\Samples\react-generic-app\node_modules\node-notifier\lib\utils.js:359:33)
    at WindowsToaster.notify (C:\NTUC\UI\sp-dev-samples\Samples\react-generic-app\node_modules\node-notifier\notifiers\toaster.js:88:19)
    at C:\NTUC\UI\sp-dev-samples\Samples\react-generic-app\node_modules\@microsoft\gulp-core-build\lib\index.js:213:46
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:26476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:26476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  Request: '/index.html'
  Request: '/node_modules/react/dist/react.js'
  Request: '/node_modules/react-dom/dist/react-dom.js'
  Request: '/dist/react-app.js'
  Request: '/dist/react-app.js'

**Comment by LawnboyMax** [comment]
Same here
